[build-system]
requires = [
  "setuptools",
  "setuptools-scm[toml]",
]
build-backend = "setuptools.build_meta"

[tool.ruff.lint]
extend-select = ["I001"]

[tool.ruff.lint.isort]
force-single-line = true
known-third-party = ["src"]
